title: MQT 2022
preposition: ''
description:  2nd Workshop on Molecular Quantum Technology
baseurl: "/" # Cambiar a "/" al momento de publicar
url: "https://mqt2022.org"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    links:
      - name: Program
        relative_url: /program/
      - name: Talks
        relative_url: /talks/
      - name: Invited Speakers
        relative_url: /speakers/
      - name: Location
        relative_url: /location/
      - name: Previous Editions
        menu:
          - name: 2019
            relative_url: /2019/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Program
        relative_url: /program/
      - name: How to get there
        relative_url: /location/

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  map:
    # Initial map center point
    home_coord: -33.45694, -70.64827
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 17

  talks:
    # Talk categories
    main_categories:
      - name: Classic Physics
        color: info
      - name: Quantum Physics
        color: success

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page
    map: true

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
